package com.fit2cloud.ticket.dao.model;

import java.io.Serializable;

public class TicketTagMapping implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket_tag_mapping.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket_tag_mapping.tag_key
     *
     * @mbg.generated
     */
    private String tagKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket_tag_mapping.ticket_config_id
     *
     * @mbg.generated
     */
    private String ticketConfigId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ticket_tag_mapping
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket_tag_mapping.id
     *
     * @return the value of ticket_tag_mapping.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket_tag_mapping.id
     *
     * @param id the value for ticket_tag_mapping.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket_tag_mapping.tag_key
     *
     * @return the value of ticket_tag_mapping.tag_key
     *
     * @mbg.generated
     */
    public String getTagKey() {
        return tagKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket_tag_mapping.tag_key
     *
     * @param tagKey the value for ticket_tag_mapping.tag_key
     *
     * @mbg.generated
     */
    public void setTagKey(String tagKey) {
        this.tagKey = tagKey == null ? null : tagKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket_tag_mapping.ticket_config_id
     *
     * @return the value of ticket_tag_mapping.ticket_config_id
     *
     * @mbg.generated
     */
    public String getTicketConfigId() {
        return ticketConfigId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket_tag_mapping.ticket_config_id
     *
     * @param ticketConfigId the value for ticket_tag_mapping.ticket_config_id
     *
     * @mbg.generated
     */
    public void setTicketConfigId(String ticketConfigId) {
        this.ticketConfigId = ticketConfigId == null ? null : ticketConfigId.trim();
    }
}