package com.fit2cloud.ticket.dao.model;

import java.io.Serializable;

public class TicketFormDeploy implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket_form_deploy.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket_form_deploy.version
     *
     * @mbg.generated
     */
    private Long version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket_form_deploy.time
     *
     * @mbg.generated
     */
    private Long time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket_form_deploy.form_id
     *
     * @mbg.generated
     */
    private String formId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket_form_deploy.content
     *
     * @mbg.generated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ticket_form_deploy
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket_form_deploy.id
     *
     * @return the value of ticket_form_deploy.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket_form_deploy.id
     *
     * @param id the value for ticket_form_deploy.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket_form_deploy.version
     *
     * @return the value of ticket_form_deploy.version
     *
     * @mbg.generated
     */
    public Long getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket_form_deploy.version
     *
     * @param version the value for ticket_form_deploy.version
     *
     * @mbg.generated
     */
    public void setVersion(Long version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket_form_deploy.time
     *
     * @return the value of ticket_form_deploy.time
     *
     * @mbg.generated
     */
    public Long getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket_form_deploy.time
     *
     * @param time the value for ticket_form_deploy.time
     *
     * @mbg.generated
     */
    public void setTime(Long time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket_form_deploy.form_id
     *
     * @return the value of ticket_form_deploy.form_id
     *
     * @mbg.generated
     */
    public String getFormId() {
        return formId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket_form_deploy.form_id
     *
     * @param formId the value for ticket_form_deploy.form_id
     *
     * @mbg.generated
     */
    public void setFormId(String formId) {
        this.formId = formId == null ? null : formId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket_form_deploy.content
     *
     * @return the value of ticket_form_deploy.content
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket_form_deploy.content
     *
     * @param content the value for ticket_form_deploy.content
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}