package com.fit2cloud.ticket.dao.model;

import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;

public class TicketForm implements Serializable {
    @ApiModelProperty("表单ID")
    private String id;

    @ApiModelProperty("表单名称")
    private String name;

    @ApiModelProperty("版本")
    private Long version;

    @ApiModelProperty("创建者")
    private String creator;

    @ApiModelProperty("部署ID")
    private String deployId;

    @ApiModelProperty("表单内容")
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ticket_form
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket_form.id
     *
     * @return the value of ticket_form.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket_form.id
     *
     * @param id the value for ticket_form.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket_form.name
     *
     * @return the value of ticket_form.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket_form.name
     *
     * @param name the value for ticket_form.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket_form.version
     *
     * @return the value of ticket_form.version
     *
     * @mbg.generated
     */
    public Long getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket_form.version
     *
     * @param version the value for ticket_form.version
     *
     * @mbg.generated
     */
    public void setVersion(Long version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket_form.creator
     *
     * @return the value of ticket_form.creator
     *
     * @mbg.generated
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket_form.creator
     *
     * @param creator the value for ticket_form.creator
     *
     * @mbg.generated
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket_form.deploy_id
     *
     * @return the value of ticket_form.deploy_id
     *
     * @mbg.generated
     */
    public String getDeployId() {
        return deployId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket_form.deploy_id
     *
     * @param deployId the value for ticket_form.deploy_id
     *
     * @mbg.generated
     */
    public void setDeployId(String deployId) {
        this.deployId = deployId == null ? null : deployId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket_form.content
     *
     * @return the value of ticket_form.content
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket_form.content
     *
     * @param content the value for ticket_form.content
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}