package com.fit2cloud.ticket.dao.model;

import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;
import java.util.Date;

public class TicketWatchList implements Serializable {
    @ApiModelProperty("id")
    private Integer id;

    @ApiModelProperty("早班值班人ID")
    private String dayUserId;

    @ApiModelProperty("早班值班人名称")
    private String dayUserName;

    @ApiModelProperty("晚班值班人ID")
    private String nightUserId;

    @ApiModelProperty("晚班值班人名称")
    private String nightUserName;

    @ApiModelProperty("值班日期")
    private Date watchDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ticket_watch_list
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket_watch_list.id
     *
     * @return the value of ticket_watch_list.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket_watch_list.id
     *
     * @param id the value for ticket_watch_list.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket_watch_list.day_user_id
     *
     * @return the value of ticket_watch_list.day_user_id
     *
     * @mbg.generated
     */
    public String getDayUserId() {
        return dayUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket_watch_list.day_user_id
     *
     * @param dayUserId the value for ticket_watch_list.day_user_id
     *
     * @mbg.generated
     */
    public void setDayUserId(String dayUserId) {
        this.dayUserId = dayUserId == null ? null : dayUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket_watch_list.day_user_name
     *
     * @return the value of ticket_watch_list.day_user_name
     *
     * @mbg.generated
     */
    public String getDayUserName() {
        return dayUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket_watch_list.day_user_name
     *
     * @param dayUserName the value for ticket_watch_list.day_user_name
     *
     * @mbg.generated
     */
    public void setDayUserName(String dayUserName) {
        this.dayUserName = dayUserName == null ? null : dayUserName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket_watch_list.night_user_id
     *
     * @return the value of ticket_watch_list.night_user_id
     *
     * @mbg.generated
     */
    public String getNightUserId() {
        return nightUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket_watch_list.night_user_id
     *
     * @param nightUserId the value for ticket_watch_list.night_user_id
     *
     * @mbg.generated
     */
    public void setNightUserId(String nightUserId) {
        this.nightUserId = nightUserId == null ? null : nightUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket_watch_list.night_user_name
     *
     * @return the value of ticket_watch_list.night_user_name
     *
     * @mbg.generated
     */
    public String getNightUserName() {
        return nightUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket_watch_list.night_user_name
     *
     * @param nightUserName the value for ticket_watch_list.night_user_name
     *
     * @mbg.generated
     */
    public void setNightUserName(String nightUserName) {
        this.nightUserName = nightUserName == null ? null : nightUserName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket_watch_list.watch_date
     *
     * @return the value of ticket_watch_list.watch_date
     *
     * @mbg.generated
     */
    public Date getWatchDate() {
        return watchDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket_watch_list.watch_date
     *
     * @param watchDate the value for ticket_watch_list.watch_date
     *
     * @mbg.generated
     */
    public void setWatchDate(Date watchDate) {
        this.watchDate = watchDate;
    }
}