package com.fit2cloud.ticket.dao.model;

import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;

public class TicketConfig implements Serializable {
    @ApiModelProperty("工单模板ID")
    private String id;

    @ApiModelProperty("工单模板名称")
    private String name;

    @ApiModelProperty("工单模板描述")
    private String description;

    @ApiModelProperty("表单ID")
    private String formId;

    @ApiModelProperty("流程模型ID")
    private String modelId;

    @ApiModelProperty("创建时间")
    private Long time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ticket_config
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket_config.id
     *
     * @return the value of ticket_config.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket_config.id
     *
     * @param id the value for ticket_config.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket_config.name
     *
     * @return the value of ticket_config.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket_config.name
     *
     * @param name the value for ticket_config.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket_config.description
     *
     * @return the value of ticket_config.description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket_config.description
     *
     * @param description the value for ticket_config.description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket_config.form_id
     *
     * @return the value of ticket_config.form_id
     *
     * @mbg.generated
     */
    public String getFormId() {
        return formId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket_config.form_id
     *
     * @param formId the value for ticket_config.form_id
     *
     * @mbg.generated
     */
    public void setFormId(String formId) {
        this.formId = formId == null ? null : formId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket_config.model_id
     *
     * @return the value of ticket_config.model_id
     *
     * @mbg.generated
     */
    public String getModelId() {
        return modelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket_config.model_id
     *
     * @param modelId the value for ticket_config.model_id
     *
     * @mbg.generated
     */
    public void setModelId(String modelId) {
        this.modelId = modelId == null ? null : modelId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket_config.time
     *
     * @return the value of ticket_config.time
     *
     * @mbg.generated
     */
    public Long getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket_config.time
     *
     * @param time the value for ticket_config.time
     *
     * @mbg.generated
     */
    public void setTime(Long time) {
        this.time = time;
    }
}