package com.fit2cloud.ticket.dao.model;

import java.io.Serializable;

public class TicketTag implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket_tag.tag_key
     *
     * @mbg.generated
     */
    private String tagKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket_tag.tag_name
     *
     * @mbg.generated
     */
    private String tagName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket_tag._index
     *
     * @mbg.generated
     */
    private Integer index;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ticket_tag
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket_tag.tag_key
     *
     * @return the value of ticket_tag.tag_key
     *
     * @mbg.generated
     */
    public String getTagKey() {
        return tagKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket_tag.tag_key
     *
     * @param tagKey the value for ticket_tag.tag_key
     *
     * @mbg.generated
     */
    public void setTagKey(String tagKey) {
        this.tagKey = tagKey == null ? null : tagKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket_tag.tag_name
     *
     * @return the value of ticket_tag.tag_name
     *
     * @mbg.generated
     */
    public String getTagName() {
        return tagName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket_tag.tag_name
     *
     * @param tagName the value for ticket_tag.tag_name
     *
     * @mbg.generated
     */
    public void setTagName(String tagName) {
        this.tagName = tagName == null ? null : tagName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket_tag._index
     *
     * @return the value of ticket_tag._index
     *
     * @mbg.generated
     */
    public Integer getIndex() {
        return index;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket_tag._index
     *
     * @param index the value for ticket_tag._index
     *
     * @mbg.generated
     */
    public void setIndex(Integer index) {
        this.index = index;
    }
}