package com.fit2cloud.ticket.dao.mapper;

import com.fit2cloud.ticket.dao.model.GHCost;
import com.fit2cloud.ticket.dao.model.GHCostExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface GHCostMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket
     *
     * @mbg.generated
     */
    long countByExample(GHCostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket
     *
     * @mbg.generated
     */
    int deleteByExample(GHCostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket
     *
     * @mbg.generated
     */
    int insert(GHCost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket
     *
     * @mbg.generated
     */
    int insertSelective(GHCost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket
     *
     * @mbg.generated
     */
    List<GHCost> selectByExampleWithBLOBs(GHCostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket
     *
     * @mbg.generated
     */
    List<GHCost> selectByExample(GHCostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket
     *
     * @mbg.GHCost
     */
    GHCost selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") GHCost record, @Param("example") GHCostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") GHCost record, @Param("example") GHCostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") GHCost record, @Param("example") GHCostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(GHCost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(GHCost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(GHCost record);

}
