package com.fit2cloud.ticket.dao.mapper;

import com.fit2cloud.ticket.dao.model.TicketConfig;
import com.fit2cloud.ticket.dao.model.TicketConfigExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TicketConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket_config
     *
     * @mbg.generated
     */
    long countByExample(TicketConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket_config
     *
     * @mbg.generated
     */
    int deleteByExample(TicketConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket_config
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket_config
     *
     * @mbg.generated
     */
    int insert(TicketConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket_config
     *
     * @mbg.generated
     */
    int insertSelective(TicketConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket_config
     *
     * @mbg.generated
     */
    List<TicketConfig> selectByExample(TicketConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket_config
     *
     * @mbg.generated
     */
    TicketConfig selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket_config
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TicketConfig record, @Param("example") TicketConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket_config
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TicketConfig record, @Param("example") TicketConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket_config
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TicketConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket_config
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TicketConfig record);
}