package com.fit2cloud.ticket.dao.mapper;

import com.fit2cloud.ticket.dao.model.TicketTag;
import com.fit2cloud.ticket.dao.model.TicketTagExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TicketTagMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket_tag
     *
     * @mbg.generated
     */
    long countByExample(TicketTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket_tag
     *
     * @mbg.generated
     */
    int deleteByExample(TicketTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket_tag
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String tagKey);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket_tag
     *
     * @mbg.generated
     */
    int insert(TicketTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket_tag
     *
     * @mbg.generated
     */
    int insertSelective(TicketTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket_tag
     *
     * @mbg.generated
     */
    List<TicketTag> selectByExample(TicketTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket_tag
     *
     * @mbg.generated
     */
    TicketTag selectByPrimaryKey(String tagKey);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket_tag
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TicketTag record, @Param("example") TicketTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket_tag
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TicketTag record, @Param("example") TicketTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket_tag
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TicketTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket_tag
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TicketTag record);
}