package com.fit2cloud.ticket.dao.mapper;

import com.fit2cloud.ticket.dao.model.TicketFormDeploy;
import com.fit2cloud.ticket.dao.model.TicketFormDeployExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TicketFormDeployMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket_form_deploy
     *
     * @mbg.generated
     */
    long countByExample(TicketFormDeployExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket_form_deploy
     *
     * @mbg.generated
     */
    int deleteByExample(TicketFormDeployExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket_form_deploy
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket_form_deploy
     *
     * @mbg.generated
     */
    int insert(TicketFormDeploy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket_form_deploy
     *
     * @mbg.generated
     */
    int insertSelective(TicketFormDeploy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket_form_deploy
     *
     * @mbg.generated
     */
    List<TicketFormDeploy> selectByExampleWithBLOBs(TicketFormDeployExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket_form_deploy
     *
     * @mbg.generated
     */
    List<TicketFormDeploy> selectByExample(TicketFormDeployExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket_form_deploy
     *
     * @mbg.generated
     */
    TicketFormDeploy selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket_form_deploy
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TicketFormDeploy record, @Param("example") TicketFormDeployExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket_form_deploy
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") TicketFormDeploy record, @Param("example") TicketFormDeployExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket_form_deploy
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TicketFormDeploy record, @Param("example") TicketFormDeployExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket_form_deploy
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TicketFormDeploy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket_form_deploy
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(TicketFormDeploy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket_form_deploy
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TicketFormDeploy record);
}