package com.fit2cloud.ticket.dao.mapper;

import com.fit2cloud.ticket.dao.model.TicketForm;
import com.fit2cloud.ticket.dao.model.TicketFormExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TicketFormMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket_form
     *
     * @mbg.generated
     */
    long countByExample(TicketFormExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket_form
     *
     * @mbg.generated
     */
    int deleteByExample(TicketFormExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket_form
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket_form
     *
     * @mbg.generated
     */
    int insert(TicketForm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket_form
     *
     * @mbg.generated
     */
    int insertSelective(TicketForm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket_form
     *
     * @mbg.generated
     */
    List<TicketForm> selectByExampleWithBLOBs(TicketFormExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket_form
     *
     * @mbg.generated
     */
    List<TicketForm> selectByExample(TicketFormExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket_form
     *
     * @mbg.generated
     */
    TicketForm selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket_form
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TicketForm record, @Param("example") TicketFormExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket_form
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") TicketForm record, @Param("example") TicketFormExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket_form
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TicketForm record, @Param("example") TicketFormExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket_form
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TicketForm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket_form
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(TicketForm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket_form
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TicketForm record);
}